version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # Management dashboard
    environment:
        RABBITMQ_DEFAULT_PASS: pass
        RABBITMQ_DEFAULT_USER: user